# -*- coding: utf-8 -*-
"""Arboles_1358.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDt9AQ7RHUfbxcQ9lcgMQYGbJlzZIy6V
"""

class BinaryNode:
  def __init__(self , value, left=None, right= None):
    self.data = value
    self.left = left
    self.right = right

class TernaryNode:
  def __init__(self , value, left=None, center=None, right= None):
    self.data = value
    self.left = left
    self.center = center
    self.right = right

root = BinaryNode("R",BinaryNode("C"),BinaryNode("H"))
print( root.left.data )

root = TernaryNode(4,TernaryNode(3,TernaryNode(5,left=TernaryNode(2)),\
                  TernaryNode(5),TernaryNode(2)), None, TernaryNode(5) )
print(root.left.left.left.data)
print(".-.-.-.-.-.-.-.-.-.")
aux = root
while aux.left != None:
  aux = aux.left
print(aux.data)
print(".-.-.-.-.-.-.-.-.-.")
print(root.left.left.left.data)

root = BinaryNode("Santi",None,\
                  BinaryNode("Jesus",BinaryNode("Pedro",None,BinaryNode("Pedro")))
print(root.right.left.right,data)